#!/bin/sh
# Create symlinks within opencode configs

ln -snf $(realpath AGENTS.md) ~/.config/opencode/AGENTS.md
ln -snf $(realpath opencode.json) ~/.config/opencode/opencode.json
ln -snf $(realpath skills) ~/.config/opencode/skills
