#!/bin/sh
# Create symlinks within opencode configs

# Use sudo to create dir because my home dir is write protected
sudo mkdir -p ~/forge
sudo chown jncraton:jncraton ~/forge

ln -snf $(realpath AGENTS.md) ~/forge/AGENTS.md
ln -snf $(realpath skills) ~/forge/skills
ln -snf $(realpath agents) ~/forge/agents

mkdir -p ~/.local/bin && curl -L -o ~/.local/bin/forge https://github.com/antinomyhq/forge/releases/download/v2.3.2/forge-x86_64-unknown-linux-musl && chmod +x ~/.local/bin/forge
